# =====================================
# STREAMLIT SECRETS — CRM SHT
# =====================================

[mysql]
host = "10.10.12.25"
port = 3306
database = "crm_sht"
user = "fabio"
password = "fabio"

[box]
developer_token = "PdgQXTYdggRPC0RF7ZS8A1LN9HVYIJs9"
backup_folder_id = "0"

[auth.users.fabio]
password = "fabio"
role = "admin"

[auth.users.gabriele]
password = "gabriele"
role = "limitato"

[auth.users.giulia]
password = "giulia"
role = "limitato"

[auth.users.antonella]
password = "antonella"
role = "limitato"
