# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#2563eb"            # blu principale
backgroundColor = "#f8fafc"         # grigio/azzurro molto chiaro
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1117"               # quasi nero

[server]
headless = true
# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#2563eb"            # blu principale
backgroundColor = "#f8fafc"         # grigio/azzurro molto chiaro
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1117"               # quasi nero

[server]
headless = true

[auth]

  [auth.users]

    [auth.users.fabio]
    password = "matrix"
    role     = "admin"

    [auth.users.emanuela]
    password = "SCEGLI-LA-TUA-PASS"
    role     = "editor"

    [auth.users.claudia]
    password = "SCEGLI-LA-TUA-PASS"
    role     = "editor"

    [auth.users.giulia]
    password = "SCEGLI-LA-TUA-PASS"
    role     = "contributor"

    [auth.users.antonella]
    password = "SCEGLI-LA-TUA-PASS"
    role     = "contributor"

