[theme]
base = "light"
primaryColor = "#2563eb"            # blu principale
backgroundColor = "#f8fafc"         # grigio/azzurro molto chiaro
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1117"               # quasi nero

[server]
headless = true
fileWatcherType = "none"            # <-- risolve l’errore “inotify watch limit reached”
[auth]
users = {
  fabio     = { password = "matrix",             role = "admin" },
  emanuela  = { password = "SCEGLI-LA-TUA-PASS", role = "editor" },
  claudia   = { password = "SCEGLI-LA-TUA-PASS", role = "editor" },
  giulia    = { password = "SCEGLI-LA-TUA-PASS", role = "contributor" },
  antonella = { password = "SCEGLI-LA-TUA-PASS", role = "contributor" }
}
