# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#2563eb"            # blu principale
backgroundColor = "#f8fafc"         # grigio/azzurro molto chiaro
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1117"               # quasi nero

[server]
headless = true
