[auth]
  [auth.users]
    fabio     = { password = "matrix",             role = "admin" }
    emanuela  = { password = "SCEGLI-LA-TUA-PASS", role = "editor" }
    claudia   = { password = "SCEGLI-LA-TUA-PASS", role = "editor" }
    giulia    = { password = "SCEGLI-LA-TUA-PASS", role = "contributor" }
    antonella = { password = "SCEGLI-LA-TUA-PASS", role = "contributor" }

[storage]
local_dir = "storage"
proposals_dir = "storage/preventivi"

[database]
url = ""
